---
abstract: 'very fast Mojo-styled accessors'
author:
  - 'Yaroslav Korshak <yko@cpan.org>'
  - 'Yaroslav Korshak <yko@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Base-XS
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
